
services:
  stars-group-web:
    container_name: stars-group-web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_BASE_URL: ${VITE_BASE_URL}
    env_file: ".env"
    restart: unless-stopped
    ports:
      - 8284:5000

