services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.pnpm
      args:
        - VITE_BASE_URL=${VITE_BASE_URL}
    restart: unless-stopped
    env_file: '.env'
    environment:
      - VITE_BASE_URL=${VITE_BASE_URL}
    ports:
      - 8284:5000
